modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="cosmicbeings"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="Cosmic Beings"
description='''
A cosmic addon for Palladium!
'''

[[dependencies.cosmicbeings]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
